repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages:
          - commit-msg
      - id: end-of-file-fixer
        stages:
          - commit-msg
      - id: check-yaml
        stages:
          - commit-msg
      - id: double-quote-string-fixer
        stages:
          - commit-msg
